name: NGX Cross-Platform Tests

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  workflow_dispatch: # Allow manual triggering

jobs:
  test:
    name: Test NGX on Multiple Platforms
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version
          
      - name: Verify Docker installation
        run: |
          docker --version
          docker-compose --version
          
      - name: Make test scripts executable
        run: |
          chmod +x docker/run-ci-tests.sh
          chmod +x docker/test-ngx.sh
          chmod +x bin/ngx
          
      - name: Run syntax check
        run: |
          bash -n bin/ngx
          echo "✓ NGX script syntax check passed"
          
      - name: Run cross-platform tests
        run: |
          cd docker
          ./run-ci-tests.sh
          
      - name: Upload test artifacts on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-logs
          path: |
            docker/*.log
            /tmp/ngx-test-*
          retention-days: 7